name: romkh
favicon: null
layout_spectrum: 0.26267
typography_spectrum: 0.74916
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.9663343373686075
  lightness: 0.022886379389092326
  saturation: 0.6646905497182161
  rhythmicContrast: 0.3329253520350903
purpose: []
